blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://aniyomi.org/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🧑‍💻 Animetail help discord
    url: https://discord.gg/Bp8ZJkNYXJ
    about: Common questions are answered here
  - name: 🖥️ Aniyomi website
    url: https://aniyomi.org/
    about: Guides, troubleshooting, and answers to common questions
